export const profileNameToBodyPartObject = {
  Vitamin: "Skin",
  Hormones: "Nervous System & Brain",
  "Inflammation Panel": "Nervous System & Brain",
  "Thyroid Profile": "Thyroid & Adrenal Glands",
  // "Hormones": "Thyroid & Adrenal Glands",
  "Bacterial Infections Panel": "Lungs",
  "Cardiac panel": "Heart & Cardiovascular System",
  "Lipid Profile": "Heart & Cardiovascular System",
  "Liver Profile": "Liver",
  "Kidney Profile": "Kidneys",
  "Electrolyte Profile": "Kidneys",
  // "Vitamin": "Digestive System",
  "Pancreatic panel": "Digestive System",
  Urinalysis: "Bladder & Urinary System",
  "STD Profile": "Reproductive Organs",
  "Fertility Panel": "Reproductive Organs",
};

export const profileNameToProfileArrayObject = {
  Vitamin: ["Vitamin"],
  Hormones: ["Hormones", "Inflammation Panel"],
  "Inflammation Panel": ["Hormones", "Inflammation Panel"],
  "Thyroid Profile": ["Thyroid Profile", "Hormones"],
  // "Hormones": "Thyroid & Adrenal Glands",
  "Bacterial Infections Panel": ["Bacterial Infections Panel"],
  "Cardiac panel": ["Cardiac panel", "Lipid Profile"],
  "Lipid Profile": ["Cardiac panel", "Lipid Profile"],
  "Liver Profile": ["Liver Profile"],
  "Kidney Profile": ["Kidney Profile", "Electrolyte Profile"],
  "Electrolyte Profile": ["Kidney Profile", "Electrolyte Profile"],
  // "Vitamin": "Digestive System",
  "Pancreatic panel": ["Vitamin", "Pancreatic panel"],
  Urinalysis: ["Urinalysis"],
  "STD Profile": ["STD Profile", "Fertility Panel"],
  "Fertility Panel": ["STD Profile", "Fertility Panel"],
};

export const bodyPartToProfileNamesObject = {
  Skin: ["Vitamin"],
  "Nervous System & Brain": ["Hormones", "Inflammation Panel"],
  "Thyroid & Adrenal Glands": ["Thyroid Profile", "Hormones"],
  Lungs: ["Bacterial Infections Panel"],
  "Heart & Cardiovascular System": ["Cardiac panel", "Lipid Profile"],
  Liver: ["Liver Profile"],
  Kidneys: ["Kidney Profile", "Electrolyte Profile"],
  "Digestive System": ["Vitamin", "Pancreatic panel"],
  "Bladder & Urinary System": ["Urinalysis"],
  "Reproductive Organs": ["STD Profile", "Fertility Panel"],
};
